parameters:
    tables.sessionghost: %core.table_prefix%session_ghost
    tables.sessionhost: %core.table_prefix%sessions_host
    tables.sessionfingerprint: %core.table_prefix%session_fingerprint

services:
    anavaro.sessionadmin.events:
        class: anavaro\sessionadmin\event\main_listener
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@user'
            - '@template'
            - '@log'
            - '@request'
            - '@controller.helper'
            - '%tables.sessionghost%'
            - '%tables.sessionhost%'
        tags:
            - { name: event.listener }
    anavaro.sessionadmin.input:
        class: anavaro\sessionadmin\controller\input
        arguments:
            - '@dbal.conn'
            - '@user'
            - '%tables.sessionfingerprint%'