parameters:
    tables.sessionghost: %core.table_prefix%session_ghost
    tables.sessionhost: %core.table_prefix%sessions_host

services:
    anavaro.sessionadmin.events:
        class: anavaro\sessionadmin\event\main_listener
        arguments:
            - @dbal.conn
            - @config
            - @user
            - %tables.sessionghost%
            - %tables.sessionhost%
        tags:
            - { name: event.listener }